query AaveMarketPositions($user: EvmAddress!, $chainIds: [ChainId!]!) {
  markets(request: { chainIds: $chainIds, user: $user }) {
    name
    address
    chain {
      chainId
      name
    }
    userState {
      healthFactor
      totalDebtBase
      totalCollateralBase
    }
  }
}
